# Generated by Django 4.0.2 on 2022-03-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_cycling_team_sports'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxing',
            name='picture',
            field=models.ImageField(default='default value', upload_to=''),
        ),
    ]
